# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4ed706fe25af1401ba27c016b855f42bf232361f445235d07165d721d58dc4a35e78b836f6992b5fa83afb69e1cc1aabf70a2bda4c8100f76bebc4c53b434f8

test:
  secret_key_base: 52874b5bcd83514c8c17c26b1286e6902aa61da7622cb801b5d2edf319533411030849c743cd838b460509c9886c08d23eb0cd1eb6c059b16a1eac4c0d48c4ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
