# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dcdacd35b0fd571a04df3df480b083f17f198943b789af6024fc572a62f4de80b6de28b27805375cf4efa95c287747b123eb6fe99a678eb9709821a567463093

test:
  secret_key_base: a3bf1a3158abaadca86c016bcedfd6a469820f266b8c1cb88da51fa4b72e2c4b4b7e86d2d29dbb8f4dca09540a089dc9bca1ee7dc9cf20959a2917e87e46c185

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
